class PatientProfileModel {
  String? firstName = "",
      lastName = "",
      mobNo = "",
      emailId = "",
      imgUrl = "",
      dob = "",
      age = "-",
      address = "",
      city = "",
      state = "",
      country = "",
      married = "",
      noOfFamilyMembers = "",
      yourPositionInFamily = "",
      countryIDF = "",
      stateIDF = "",
      cityIDF = "",
      middleName = "",
      weight = "",
      height = "",
      bloodGroup = "",
      emergencyNumber = "",
      gender = "",
      speciality = "",
      practisingSince = "",
      residenceAddress = "",
      residenceMobileNo = "",
      residenceLandLineNo = "",
      businessAddress = "",
      businessMobileNo = "",
      businessLandLineNo = "",
      businessCity = "",
      businessState = "",
      businessCountry = "",
      businessCityIDP = "",
      businessStateIDP = "",
      businessCountryIDP = "",
      degree = "",
      patientID = "",
      registrationNumber = "",
      whatsAppNumber = "",
      appointmentNumber = "",
      latitude = "",
      longitude = "",
      specialityIDP = "";

  PatientProfileModel(
    this.firstName,
    this.lastName,
    this.mobNo,
    this.emailId,
    this.imgUrl,
    this.dob,
    this.age,
    this.address,
    this.city,
    this.state,
    this.country,
    this.married,
    this.noOfFamilyMembers,
    this.yourPositionInFamily,
    this.countryIDF,
    this.stateIDF,
    this.cityIDF,
    this.middleName,
    this.weight,
    this.height,
    this.bloodGroup,
    this.emergencyNumber,
    this.gender, {
    this.speciality,
    this.practisingSince,
    this.residenceAddress,
    this.residenceMobileNo,
    this.residenceLandLineNo,
    this.businessAddress,
    this.businessMobileNo,
    this.businessLandLineNo,
    this.businessCity = "",
    this.businessState = "",
    this.businessCountry = "",
    this.businessCityIDP = "",
    this.businessStateIDP = "",
    this.businessCountryIDP = "",
    this.degree = "",
    this.patientID = "",
    this.registrationNumber = "",
    this.whatsAppNumber = "",
    this.appointmentNumber = "",
    this.latitude = "",
    this.longitude = "",
    this.specialityIDP = "",
  });
}
